apiVersion: v1
kind: Service
metadata:
  name: django-microservice
spec:
  selector:
    app: django-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
